### ISSUE TITLE
Am I misreading the Makefile compile target?

### ISSUE THREAD

**Issue by natemarks** [esenac/aws-lambda-go#3]
it looks like it writes the executable to a directory that's not mounted, so you can access/deploy it?

**Comment by esenac** [comment]
Hey @natemarks, sorry for the delay. I'll investigate your issue soon and let you know. At a first glance, I'd say that `bin` folder is in the golang image, but I'll double check it. 
Thanks for opening this issue!

**Comment by esenac** [comment]
Hi @natemarks, I've checked and since we're mounting `$(pwd):/app`, we can create `bin` folder under `app`. Does it make sense to you?

**Comment by natemarks** [comment]
got it. thanks!

>

**Comment by esenac** [comment]
You're welcome! Thanks again for filing the issue. I'm going to close it.
