### ISSUE TITLE
terraform.tfstate: is a directory

### ISSUE THREAD

**Issue by dm-grinko** [esenac/aws-lambda-go#4]
When I run `make compile` I'm facing this error message -
`Error: Error loading state: Failed to read state file: The state file could not be read: read terraform.tfstate: is a directory`

**Comment by esenac** [comment]
@dm-grinko thanks for the issue, I'll check this in the next few days.

**Comment by esenac** [comment]
Hi @dm-grinko , I can not replicate the issue. Could you please provide further details?
